services:
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pg-data-memento-mori:/var/lib/mementomori/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
      - memento-mori-network-ext
  rails:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    depends_on:
      - postgres
#      - memcached
    volumes:
      - .:/app
    environment:
      EDITOR: nano --wait
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    networks:
      - memento-mori-network-ext
  mailhog:
    image: mailhog/mailhog
    depends_on:
      - rails
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - memento-mori-network-ext
#  memcached:
#    image: memcached:1.6.31-alpine
#    restart: unless-stopped
#    ports:
#      - "11211:11211"
#    command: [ "-m", "1024" ]
#    networks:
#      - memento-mori-network-ext
volumes:
  pg-data-memento-mori:
    driver: local

networks:
  memento-mori-network-ext:
    external: true