# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  periodic_generate_weeks_in_life:
    class: GenerateWeeksInLifeJob
    queue: background
    schedule: "1 0 * * *"

development:
  periodic_generate_weeks_in_life:
    class: GenerateWeeksInLifeJob
    queue: background
    schedule: "* * * * *"